// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCroW9QwADJ9SYrLDuWjXSr80yUzR_zHbE',
    appId: '1:453600262733:web:96ec813087188e01c53a04',
    messagingSenderId: '453600262733',
    projectId: 'glowywallpaper',
    authDomain: 'glowywallpaper.firebaseapp.com',
    storageBucket: 'glowywallpaper.firebasestorage.app',
    measurementId: 'G-ENK459GBPX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsyPp7O2YUlZFvilIDbc82eiUdz2FbP3E',
    appId: '1:453600262733:ios:6e38a7a863fc66e9c53a04',
    messagingSenderId: '453600262733',
    projectId: 'glowywallpaper',
    storageBucket: 'glowywallpaper.firebasestorage.app',
    iosBundleId: 'com.example.glowyWallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCroW9QwADJ9SYrLDuWjXSr80yUzR_zHbE',
    appId: '1:453600262733:web:76281521793caa7bc53a04',
    messagingSenderId: '453600262733',
    projectId: 'glowywallpaper',
    authDomain: 'glowywallpaper.firebaseapp.com',
    storageBucket: 'glowywallpaper.firebasestorage.app',
    measurementId: 'G-1T4QGYD6L3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsyPp7O2YUlZFvilIDbc82eiUdz2FbP3E',
    appId: '1:453600262733:ios:5aa2633513b7071ac53a04',
    messagingSenderId: '453600262733',
    projectId: 'glowywallpaper',
    storageBucket: 'glowywallpaper.firebasestorage.app',
    iosBundleId: 'com.glowy.wallpaper',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk3jmq3_kjxZkrxamXDtObPxTfiaalIyY',
    appId: '1:453600262733:android:6e45b83c936dd334c53a04',
    messagingSenderId: '453600262733',
    projectId: 'glowywallpaper',
    storageBucket: 'glowywallpaper.firebasestorage.app',
  );

}